import * as cheerio from 'cheerio';
import * as fs from 'fs';

async function crawl() {
    console.log("Starting Moloni API Crawler v2...");
    const baseUrl = 'https://www.moloni.pt';
    
    // 1. Fetch main page to get all sidebar links
    const res = await fetch(`${baseUrl}/dev/`);
    const html = await res.text();
    const $ = cheerio.load(html);
    
    const links: {title: string, url: string}[] = [];
    
    $('.sidebarSubCatText a').each((_, el) => {
        const url = $(el).attr('href');
        const title = $(el).text().trim();
        if (url && url.startsWith('http')) {
            links.push({ title, url });
        }
    });
    
    console.log(`Found ${links.length} API endpoints.`);
    
    let markdown = `# Moloni API Detailed Functionalities (Crawled)\n\n`;
    markdown += `This document was automatically generated by crawling the Moloni API documentation.\n\n`;
    
    // Process sequentially
    for (let i = 0; i < links.length; i++) {
        const link = links[i];
        console.log(`[${i+1}/${links.length}] Fetching ${link.title}...`);
        
        try {
            const pageRes = await fetch(link.url);
            const pageHtml = await pageRes.text();
            const $page = cheerio.load(pageHtml);
            
            markdown += `## ${link.title}\n`;
            markdown += `**Category URL:** ${link.url}\n\n`;
            
            let foundMethods = false;
            
            // Look for methods in the page
            $page('.sectionHoldCat').each((_, el) => {
                const methodName = $page(el).find('.sectionCatName').text().trim();
                const methodUrl = $page(el).find('.sectionCatName').attr('href') || "";
                let methodDesc = $page(el).find('.sectionCatText').text().trim();
                // cleanup description spaces
                methodDesc = methodDesc.replace(/\s+/g, ' ');
                
                if (methodName) {
                    foundMethods = true;
                    markdown += `### \`${methodName}\`\n`;
                    markdown += `- **Endpoint:** \`${methodUrl}\`\n`;
                    markdown += `- **Description:** ${methodDesc}\n\n`;
                }
            });
            
            if (!foundMethods) {
                markdown += `*No specific methods listed on this index page.*\n\n`;
            }
            
            // Add a small delay
            await new Promise(r => setTimeout(r, 200));
            
        } catch(e) {
            console.error(`Error fetching ${link.url}:`, e);
        }
    }
    
    const outPath = '/Users/macuser/.gemini/antigravity-ide/brain/6fb3c13e-0c78-401c-88f4-d11421721c20/moloni_api_functionalities_detailed.md';
    fs.writeFileSync(outPath, markdown);
    console.log(`Saved to ${outPath}`);
}

crawl().catch(console.error);
