import { TrackingShipment } from "./types"

export const DEMO_TRACKING_SHIPMENTS: TrackingShipment[] = [
  {
    id: "LTK-8921-PT",
    displayId: "#LTK-8921-PT",
    trackingNumber: "DA892134567PT",
    status: "active",
    statusLabel: "Em Trânsito",
    carrier: "Linke Express / CTT Expresso",
    serviceType: "Serviço Nacional 24h",
    isRealData: true,
    origin: {
      hubName: "Hub Central Lisboa (Prior Velho)",
      city: "Lisboa",
      postalCode: "2685-012",
      address: "Rua do Entreposto Logístico 14, Prior Velho",
      departureTime: "Hoje, 08:30",
      lat: 38.784,
      lng: -9.125
    },
    destination: {
      hubName: "Hospital São João - Bloco Norte",
      city: "Porto",
      postalCode: "4200-319",
      address: "Alameda Prof. Hernâni Monteiro, Porto",
      eta: "Hoje, 15:45",
      etaDate: "Previsto em ~2h 15m",
      lat: 41.182,
      lng: -8.601
    },
    cargo: {
      weightStr: "740 kg",
      volumeStr: "4.8 m³",
      packagesCount: 14,
      category: "Material Hospitalar & Farmacêutico",
      clientName: "Biotec Pharma Portugal, S.A."
    },
    metrics: {
      totalDistanceKm: 315,
      remainingDistanceKm: 125,
      remainingTimeStr: "2h 15m",
      lastPickagemLocation: "Centro de Tratamento Coimbra (Taveiro)",
      lastPickagemTime: "13:00",
      lastPickagemStatus: "Triagem Concluída",
      progressPercent: 68,
      completedScansCount: 4,
      totalScansCount: 6
    },
    pickagens: [
      {
        id: "p1",
        code: "REC",
        title: "Recolha no Cliente",
        locationName: "Instalações Biotec Pharma (Prior Velho)",
        city: "Lisboa",
        postalCode: "2685-012",
        lat: 38.784,
        lng: -9.125,
        timestamp: "2026-10-08T08:30:00Z",
        formattedTime: "08:30",
        status: "completed",
        operator: "Operador Rota Lisboa #14",
        scannerDevice: "PDA-Zebra-L04",
        description: "14 volumes aceites e conferidos com guia de transporte"
      },
      {
        id: "p2",
        code: "ENT",
        title: "Entrada em Centro de Tratamento",
        locationName: "CTC Lisboa (Cabo Ruivo)",
        city: "Lisboa",
        postalCode: "1800-001",
        lat: 38.761,
        lng: -9.102,
        timestamp: "2026-10-08T09:45:00Z",
        formattedTime: "09:45",
        status: "completed",
        operator: "Cais de Descarga 02",
        scannerDevice: "Scanner Fixo Sorter D02",
        description: "Leitura de báscula e etiquetagem RFID de itinerário"
      },
      {
        id: "p3",
        code: "TRI",
        title: "Triagem Automática e Encaminhamento",
        locationName: "Hub Logístico Santarém / A1",
        city: "Santarém",
        postalCode: "2000-014",
        lat: 39.236,
        lng: -8.685,
        timestamp: "2026-10-08T11:15:00Z",
        formattedTime: "11:15",
        status: "completed",
        operator: "Linha de Triagem Rápida Norte",
        scannerDevice: "Optical Sorter Barcode-03",
        description: "Mercadoria consolidada no transporte de linha Lisboa-Porto"
      },
      {
        id: "p4",
        code: "TRN",
        title: "Chegada a Centro de Trânsito",
        locationName: "Centro de Tratamento Coimbra (Taveiro)",
        city: "Coimbra",
        postalCode: "3045-508",
        lat: 40.231,
        lng: -8.435,
        timestamp: "2026-10-08T13:00:00Z",
        formattedTime: "13:00",
        status: "current",
        isCurrentPosition: true,
        operator: "Plataforma de Baldeação",
        scannerDevice: "PDA Terminal Móvel C-08",
        description: "Leitura efetuada na receção. Carga em trânsito para a Maia"
      },
      {
        id: "p5",
        code: "DIS",
        title: "Entrada em Distribuição Local",
        locationName: "Centro Operacional Maia",
        city: "Maia (Porto)",
        postalCode: "4470-200",
        lat: 41.229,
        lng: -8.621,
        timestamp: "2026-10-08T14:30:00Z",
        formattedTime: "14:30 (Prev.)",
        status: "pending",
        operator: "Equipa de Distribuição Urbana",
        description: "Aguardando chegada para integração no circuito de entrega"
      },
      {
        id: "p6",
        code: "ETG",
        title: "Entrega no Destinatário",
        locationName: "Hospital São João - Receção Farmácia",
        city: "Porto",
        postalCode: "4200-319",
        lat: 41.182,
        lng: -8.601,
        timestamp: "2026-10-08T15:45:00Z",
        formattedTime: "15:45 (Prev.)",
        status: "pending",
        description: "Entrega com comprovativo de assinatura digital"
      }
    ],
    documentation: {
      guiaNumber: "GT-2026/08921",
      atDocCode: "AT-DOC-789123-PT26",
      issueDate: "2026-10-08 08:15",
      senderName: "Biotec Pharma Portugal, S.A.",
      senderVat: "PT 509 881 224",
      senderAddress: "Rua dos Laboratórios 10, Prior Velho",
      recipientName: "Hospital São João - Bloco Norte",
      recipientVat: "PT 503 124 990",
      recipientAddress: "Alameda Prof. Hernâni Monteiro, 4200-319 Porto",
      goodsDescription: "Produtos farmacêuticos termossensíveis em caixas isotérmicas",
      cargoWeightKg: 740,
      cargoPackages: 14,
      insuredValueEur: 42500
    }
  },
  {
    id: "LTK-9402-PT",
    displayId: "#LTK-9402-PT",
    trackingNumber: "DA940288120PT",
    status: "arriving",
    statusLabel: "A Chegar",
    carrier: "Linke Distribuição Sul",
    serviceType: "Distribuição Regional 12h",
    isRealData: true,
    origin: {
      hubName: "Centro Logístico Sintra (Mem Martins)",
      city: "Sintra",
      postalCode: "2725-397",
      address: "Parque Industrial Alto do Forte, Sintra",
      departureTime: "Hoje, 06:15",
      lat: 38.798,
      lng: -9.388
    },
    destination: {
      hubName: "Algarve Digital Store Lda",
      city: "Faro",
      postalCode: "8005-146",
      address: "Estrada do Aeroporto Km 3, Faro",
      eta: "Hoje, 11:45",
      etaDate: "Previsto em ~20m",
      lat: 37.019,
      lng: -7.930
    },
    cargo: {
      weightStr: "380 kg",
      volumeStr: "2.5 m³",
      packagesCount: 8,
      category: "Eletrónica & Informática",
      clientName: "TechLog Global Iberia"
    },
    metrics: {
      totalDistanceKm: 280,
      remainingDistanceKm: 18,
      remainingTimeStr: "20m",
      lastPickagemLocation: "Ponto de Distribuição Loulé / Faro Norte",
      lastPickagemTime: "11:10",
      lastPickagemStatus: "Em Distribuição Final",
      progressPercent: 92,
      completedScansCount: 4,
      totalScansCount: 5
    },
    pickagens: [
      {
        id: "p1",
        code: "REC",
        title: "Recolha de Mercadoria",
        locationName: "Cais Central Sintra",
        city: "Sintra",
        postalCode: "2725-397",
        lat: 38.798,
        lng: -9.388,
        timestamp: "2026-10-08T06:15:00Z",
        formattedTime: "06:15",
        status: "completed",
        scannerDevice: "Scanner Doca 01",
        description: "8 volumes carregados e validados"
      },
      {
        id: "p2",
        code: "ENT",
        title: "Passagem em Hub Alentejo",
        locationName: "Ponto Logístico Grândola (A2)",
        city: "Grândola",
        postalCode: "7570-100",
        lat: 38.177,
        lng: -8.566,
        timestamp: "2026-10-08T08:20:00Z",
        formattedTime: "08:20",
        status: "completed",
        scannerDevice: "Scanner de Linha A2-01",
        description: "Validação de itinerário intermédio"
      },
      {
        id: "p3",
        code: "TRN",
        title: "Triagem de Chegada ao Algarve",
        locationName: "Plataforma Aljustrel / Ourique",
        city: "Aljustrel",
        postalCode: "7600-011",
        lat: 37.876,
        lng: -8.163,
        timestamp: "2026-10-08T09:45:00Z",
        formattedTime: "09:45",
        status: "completed",
        scannerDevice: "PDA Terminal Móvel S-02",
        description: "Controlo de volumes efetuado"
      },
      {
        id: "p4",
        code: "DIS",
        title: "Saída para Entrega Final",
        locationName: "Centro de Distribuição Loulé / Faro Norte",
        city: "Loulé",
        postalCode: "8100-200",
        lat: 37.138,
        lng: -8.022,
        timestamp: "2026-10-08T11:10:00Z",
        formattedTime: "11:10",
        status: "current",
        isCurrentPosition: true,
        scannerDevice: "PDA Distribuidor #44",
        description: "Volume em carrinha de entrega final. Destinatário alertado via SMS"
      },
      {
        id: "p5",
        code: "ETG",
        title: "Entrega Prevista",
        locationName: "Algarve Digital Store Lda",
        city: "Faro",
        postalCode: "8005-146",
        lat: 37.019,
        lng: -7.930,
        timestamp: "2026-10-08T11:45:00Z",
        formattedTime: "11:45 (Prev.)",
        status: "pending",
        description: "Aguardando confirmação de entrega ao balcão"
      }
    ],
    documentation: {
      guiaNumber: "GT-2026/09402",
      atDocCode: "AT-DOC-612984-PT26",
      issueDate: "2026-10-08 06:00",
      senderName: "TechLog Global Iberia",
      senderVat: "PT 514 902 331",
      senderAddress: "Parque Industrial Alto do Forte, Sintra",
      recipientName: "Algarve Digital Store Lda",
      recipientVat: "PT 508 190 220",
      recipientAddress: "Estrada do Aeroporto Km 3, Faro",
      goodsDescription: "Servidores em rack e componentes de rede de alta densidade",
      cargoWeightKg: 380,
      cargoPackages: 8,
      insuredValueEur: 18500
    }
  },
  {
    id: "LTK-7810-PT",
    displayId: "#LTK-7810-PT",
    trackingNumber: "DA781044321PT",
    status: "departed",
    statusLabel: "Partida Recente",
    carrier: "Linke Carga Geral",
    serviceType: "Transporte LTL Interurbano",
    isRealData: true,
    origin: {
      hubName: "Parque Logístico Braga (Celeirós)",
      city: "Braga",
      postalCode: "4705-414",
      address: "Rua do Parque Industrial 50, Braga",
      departureTime: "Hoje, 10:10",
      lat: 41.516,
      lng: -8.441
    },
    destination: {
      hubName: "Centro de Distribuição Coimbra",
      city: "Coimbra",
      postalCode: "3025-045",
      address: "Zona Industrial da Pedrulha, Coimbra",
      eta: "Hoje, 12:45",
      etaDate: "Previsto em ~1h 50m",
      lat: 40.231,
      lng: -8.435
    },
    cargo: {
      weightStr: "1.120 kg",
      volumeStr: "7.2 m³",
      packagesCount: 22,
      category: "Têxteis & Vestuário de Exportação",
      clientName: "ModaNorte Confecções, Lda"
    },
    metrics: {
      totalDistanceKm: 165,
      remainingDistanceKm: 142,
      remainingTimeStr: "1h 50m",
      lastPickagemLocation: "Pórtico A3 - Famalicão",
      lastPickagemTime: "10:35",
      lastPickagemStatus: "Em Rota",
      progressPercent: 18,
      completedScansCount: 2,
      totalScansCount: 4
    },
    pickagens: [
      {
        id: "p1",
        code: "REC",
        title: "Partida da Origem",
        locationName: "Cais 04 Celeirós",
        city: "Braga",
        postalCode: "4705-414",
        lat: 41.516,
        lng: -8.441,
        timestamp: "2026-10-08T10:10:00Z",
        formattedTime: "10:10",
        status: "completed",
        scannerDevice: "Scanner Báscula Celeirós",
        description: "22 volumes etiquetados e pesados"
      },
      {
        id: "p2",
        code: "TRN",
        title: "Leitura de Passagem em Linha",
        locationName: "Pórtico A3 - Vila Nova de Famalicão",
        city: "Vila Nova de Famalicão",
        postalCode: "4760-001",
        lat: 41.408,
        lng: -8.519,
        timestamp: "2026-10-08T10:35:00Z",
        formattedTime: "10:35",
        status: "current",
        isCurrentPosition: true,
        scannerDevice: "Leitor Automático de Matrícula/RFID",
        description: "Itinerário validado em autoestrada A3 sentido Sul"
      },
      {
        id: "p3",
        code: "TRI",
        title: "Nó de Ligação A1 Porto Sul",
        locationName: "Hub de Ligação Albergaria-a-Velha",
        city: "Albergaria-a-Velha",
        postalCode: "3850-001",
        lat: 40.693,
        lng: -8.480,
        timestamp: "2026-10-08T12:00:00Z",
        formattedTime: "12:00 (Prev.)",
        status: "pending",
        description: "Baldeação para viatura de entrega regional"
      },
      {
        id: "p4",
        code: "ETG",
        title: "Entrega em Centro de Coimbra",
        locationName: "Zona Industrial da Pedrulha",
        city: "Coimbra",
        postalCode: "3025-045",
        lat: 40.231,
        lng: -8.435,
        timestamp: "2026-10-08T12:45:00Z",
        formattedTime: "12:45 (Prev.)",
        status: "pending",
        description: "Descarga no cais com guia rubricada"
      }
    ],
    documentation: {
      guiaNumber: "GT-2026/07810",
      atDocCode: "AT-DOC-448190-PT26",
      issueDate: "2026-10-08 09:50",
      senderName: "ModaNorte Confecções, Lda",
      senderVat: "PT 502 884 100",
      senderAddress: "Rua do Parque Industrial 50, Braga",
      recipientName: "Centro de Moda Centro S.A.",
      recipientVat: "PT 501 339 211",
      recipientAddress: "Zona Industrial da Pedrulha, Coimbra",
      goodsDescription: "Caixas de vestuário pendurado e embalado para pronto-a-vestir",
      cargoWeightKg: 1120,
      cargoPackages: 22,
      insuredValueEur: 29800
    }
  }
]
